### ISSUE TITLE
Unregister only when destroy

### ISSUE THREAD

**Issue by e-minguez** [projectatomic/adb-vagrant-registration#35]
Wouldn't be useful a flag that doesn't unregister the environment when you halt it, but only when you destroy it?

**Comment by strzibny** [comment]
We could probably make this optional/configurable in the Vagrantfile itself.

**Comment by e-minguez** [comment]
Sure, thanks!

**Comment by strzibny** [comment]
This should be done in https://github.com/projectatomic/adb-vagrant-registration/commit/2570a34cfbc34cb1cf261c26145a59e74aacbe90. I released it as `0.0.18`. If you can, help me to test it. Here is the documentation: https://github.com/projectatomic/adb-vagrant-registration#plugin-configuration.

**Comment by whitel** [comment]
By way of background, the reason it unregisters on halt is because many people just halt a VM when they are done with a project. By only halting the VM they can store it off on some cold storage in the exact state it was when they last worked on the project. So, when a bug comes back, it is right there :). Leaving a VM registered in those conditions would not be cool.
