### ISSUE TITLE
Add support to enable and disable repos

### ISSUE THREAD

**Issue by e-minguez** [projectatomic/adb-vagrant-registration#37]
It would be nice to add support for enabling or disabling repos

**Comment by strzibny** [comment]
Yes, we were thinking about this one. At this moment we only support `register` subcommand or `subcription-manager` but I also see that enabling repos for provisioning would be very handy.

**Comment by whitel** [comment]
Personally, I think this is the job of config management. Once the registration happens, config management can take over and do all the things they do well. One of the reasons I originally built v-reg was because I needed to get the registration done before *any* of the provision steps, however, I never wanted to try to do all the things a provisioner does. Take a look at vagrant & ansible for some easy/good solutions to enabling / disabling repos.

I also, hoped, that v-registration could be semi-generic and people could use it to enable other subscription type products. However, that seems to have fallen a bit by the wayside :)
