### ISSUE TITLE
Support proxies

### ISSUE THREAD

**Issue by e-minguez** [projectatomic/adb-vagrant-registration#65]
It would be nice to have parameters to specify proxies, because I've tried vagrant-proxy but it set the proxy after vagrant-registration plugin :(

**Comment by ricfeatherstone** [comment]
+1

**Comment by pvalena** [comment]
Can you please test the issue with our newest release 1.2.2?
The hooks were changed, so the vagrant-proxy may be set up before this plugin.

**Comment by hferentschik** [comment]
Using vagrant-proxyconf would imply that rhn_register respects HTTP_PROXY environment variables. Does it? There is no specific code in vagrant-proxyconf which would otherwise pass the right thing to rhn_register.

rhn_register does have the required options:

    Usage: rhn_register [options]
    
    Options:
      -v, --verbose         Show additional output
      --proxy=PROXY         Specify an http proxy to use
      --proxyUser=PROXYUSER
                            Specify a username to use with an authenticated http
                            proxy
      --proxyPassword=PROXYPASSWORD
                            Specify a password to use with an authenticated http
                            proxy
      --version             show program's version number and exit
      -h, --help            show this help message and exit
      --nox                 Do not attempt to use X

one would just have to pass them through via Vagrant plugin options. 

Making use of vagrant-proxyconf requires really two things:

* The plugin runs before vagrant-registration
* rhn_register respects general proxy settings (without the need to explicitly set the existing command line options)

IMO the safest path is to expose proxy config options for vagrant-registration.

**Comment by hferentschik** [comment]
Hmm, actually the default might be subscription-manager, but it's basically the same.

**Comment by hferentschik** [comment]
Merged
